### ISSUE TITLE
Doesn't wait for upload to finish

### ISSUE THREAD

**Issue by TomixUG** [fawazahmed0/youtube-uploader#131]
Hi, 
the program starts uploading the video and correctly sets all the options, but the browser closes before the upload finishes. 
I am using the latest version: 1.3.60

This is what onProgress outputs:
```
progress { progress: 0, stage: 0 }
progress { progress: 1, stage: 0 }
progress { progress: 2, stage: 0 }
progress { progress: 3, stage: 0 }
progress { progress: 4, stage: 0 }
progress { progress: 5, stage: 0 }
progress { progress: 6, stage: 0 }
progress { progress: 0, stage: 1 }
progress { progress: 100, stage: 2 }
[ 'https://youtu.be/KC1byrOsAVkp' ]
```

**Comment by fawazahmed0** [comment]
Thanks, try 1.3.61

**Comment by DominicFindlay** [comment]
Hi,
Does the skipProcessingWait option work anymore?
As it waits a long time before ending.

What does the `,{ hidden: true ...` bit mean? on line 170 and 178.


My use doesn't need to wait for processing.

**Comment by DominicFindlay** [comment]
I have tried with a tiny video file, where youtube abandons processing, is this the case these changes are intended to fix?

**Comment by fawazahmed0** [comment]
I don't regularly test this package, so I am not sure if skipProcessingWait is still working or not. I am dependent on people who regularly use this package to report bugs in this package.

Also you should consider asking about `{ hidden: true ... ` questions at https://github.com/fawazahmed0/youtube-uploader/pull/125 to sacredrel1c .  I only reverted changes done by sacredrel1c  because it was causing issues
