### ISSUE TITLE
We gotta handle recovery phone number

### ISSUE THREAD

**Issue by pierreminiggio** [fawazahmed0/youtube-uploader#21]
![image](https://user-images.githubusercontent.com/35456349/124657270-991fd300-dea2-11eb-8f5b-e50fd8078f74.png)

**Comment by fawazahmed0** [comment]
Have you done [this](https://github.com/fawazahmed0/youtube-uploader#youtube-setup)

**Comment by pierreminiggio** [comment]
My bad I did not.

**Comment by fawazahmed0** [comment]
I hope it should be fixed now after you do those steps.

Thanks

**Comment by pierreminiggio** [comment]
Now it asks for a code on my email :'(
I guess that's not enough
![image](https://user-images.githubusercontent.com/35456349/124661826-54973600-dea8-11eb-823e-37dd3afa8b5c.png)

**Comment by fawazahmed0** [comment]
Do you have recovery email?

**Comment by fawazahmed0** [comment]
Also you need to pass that recovery email in credentials:
`const credentials = { email: 'email', pass: 'pass', recoveryemail: 'Your Recovery Email' }`

**Comment by pierreminiggio** [comment]
Yes I passed the recovery email in the "recoveryemail" key.

Actually it's the google account that I'm using that is weird, his recovery email is the same email as my login email, and I can't change it, unlike on my other google accounts.

Maybe that's because of that, I'll try using another google account.

**Comment by fawazahmed0** [comment]
You can change recovery email by [here](https://myaccount.google.com/recovery/email)

**Comment by pierreminiggio** [comment]
Yup ik I changed it.
Now I get this : 
![image](https://user-images.githubusercontent.com/35456349/124666402-45b38200-deae-11eb-9883-279045f4e6f8.png)

(PS I'm getting all these issues because I'm moving my script to my production server and using a proxy to still act like I'm home, but I guess Google still detects that something is different).

**Comment by fawazahmed0** [comment]
Is it working now?
I also faced those issues when I made this [project](https://github.com/fawazahmed0/quran-videos/), also I don't think there is a need for proxy, you can see [here](https://www.youtube.com/user/JavaDB9/playlists) & [here](https://www.youtube.com/results?search_query=javadb9) , I have uploaded around 10,561 videos using the same code(using Free Github Actions), but remember you need to upload less than 100 videos per day otherwise youtube will restrict your daily upload limit.

Also [this](https://github.com/fawazahmed0/quran-videos/issues/50) might be relevant.

Once it's starts working(i.e uploading videos from your production server), I believe you won't face any issue again.

Thanks

**Comment by pierreminiggio** [comment]
It's working on one of my accounts.
I just got it to work on a second one. Been stuck on a random error that turned out that only been caused by a bad password...

Also Google asked for some of my accounts to confirm on my phone that it's me logging in, despite me disabling that verification.
So i've to verify it once using my phone, and then it seems to be okey.

I'll close this issue.
